### ISSUE TITLE
`OPENSSL_1_1_1' not found & GLIBC_2.28' not found

### ISSUE THREAD

**Issue by IthildinX** [jumpsmm7/pixelserv-tls2.30.deb#1]
There are wrong messages when I run pixelserv-tls on my Raspberry Pi:

pixelserv-tls: /usr/lib/arm-linux-gnueabihf/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by pixelserv-tls)
pixelserv-tls: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by pixelserv-tls)

**Comment by jumpsmm7** [comment]
> 
> 
> There are wrong messages when I run pixelserv-tls on my Raspberry Pi:
> 
> pixelserv-tls: /usr/lib/arm-linux-gnueabihf/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by pixelserv-tls) pixelserv-tls: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by pixelserv-tls)

The correct issue tracker is here https://github.com/kvic-z/pixelserv-tls/issues/32 .
it appears you do not have the correct version of openssl. 
Two things that must be true for you to use this dpkg package, first -you must be running the Default RaspbianOS on your raspberry pi (this wont work for ubuntu-mate or any other OS installed on a Raspberry PI). IF you are running RaspbianOS, to get the lastest pieces of the puzzle, you may need to update your kernal version.
my suggestion to you is 
`sudo apt update`
`sudo apt dist-upgrade -y`
`sudo apt clean`
`sudo reboot`
unless you know how to install or compile these dependencies yourself. 

then after this, follow the install process again with a clean start from the beginning of the install process.
instructions are posted here
@ https://github.com/jumpsmm7/pixelserv-tls_2.3.1-1_armhf.deb/blob/master/README.md

**Comment by jumpsmm7** [comment]
for the parts that you need,you could also try.
`sudo apt install libssl1.1 libssl1.0.2 glibc-source`
