### ISSUE TITLE
Version for Debian amd64 please

### ISSUE THREAD

**Issue by gspannu** [jumpsmm7/pixelserv-tls2.30.deb#3]
Can you please publish a Debian amd64 version please?

**I am trying to install Pixelserv-tls on a Cloud Hosted Debian11 x64 along with AdGuard Home.**

Could you please **release a Debian amd64 package** along with some **instructions** to 
- auto start at boot 
- server address configured as  IP address x.y.z.a

**Comment by jumpsmm7** [comment]
> Can you please publish a Debian amd64 version please?
> 
> **I am trying to install Pixelserv-tls on a Cloud Hosted Debian11 x64 along with AdGuard Home.**
> 
> Could you please **release a Debian amd64 package** along with some **instructions** to
> 
> * auto start at boot
> * server address configured as  IP address x.y.z.a

I am sorry to disappoint, but I won't be packaging for anything greater than arm7hf for Raspbian. The directions I provide for the raspbian .deb would be the same for the Debian amd64 meaning the deb file i provide installs all the required items for starting at boot and directions for setting up the ip, the package just has to be enabled as a service.. I don't have the reasources to package it for amd64. Your best bet would be to try to install from the pixelservtls github. From my understanding, one of the last commits was to add Debian packaging setup. That would be your best option. Or look at Arch Linux method for packaging.

**Comment by gspannu** [comment]
Thanks...
